from turtle import *
while True:
    print("Какую фигуру вы хотите нарисовать")
    print("1.Квадрат")
    print("2.Премоугольник")
    print("3.Треуольник")
    print("4.Круг")
    chois = input("Введите номер выбраной фигуры: ")
    clear()
    if chois == "1":
        clear()
        forward(200)
        left(90)
        forward(200)
        left(90)
        forward(200)
        left(90)
        forward(200)
        left(90)
    elif chois == "2":
        clear()
        forward(100)
        left(90)
        forward(200)
        left(90)
        forward(100)
        left(90)
        forward(200)
        left(90)
    elif chois == "3":
        clear()
        forward(100)
        left(120)
        forward(100)
        left(120)
        forward(100)
    elif chois == "4":
        clear()
        chois_2 = int(input("Введите радиус круга"))
        circle(chois_2)
    setheading(0)
clear()
mainloop()